//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouiToolkit.ConvertJsToSvg.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YouiToolkit.ConvertJsToSvg.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !function(c){var h,a,l,z,v,o=&apos;&lt;svg&gt;&lt;symbol id=&quot;icon-GET_INVENTORY_RESULT&quot; viewBox=&quot;0 0 1024 1024&quot;&gt;&lt;path d=&quot;M867 864c-5.9 0-11.8-2.2-16.3-6.7l-83.5-83.5c-9-9-9-23.5 0-32.5s23.5-9 32.5 0l83.5 83.5c9 9 9 23.5 0 32.5-4.4 4.5-10.3 6.7-16.2 6.7z&quot;  &gt;&lt;/path&gt;&lt;path d=&quot;M868 864c-5.9 0-11.8-2.2-16.3-6.7l-83.5-83.5c-9-9-9-23.5 0-32.5s23.5-9 32.5 0l83.5 83.5c9 9 9 23.5 0 32.5-4.4 4.5-10.3 6.7-16.2 6.7z&quot;  &gt;&lt;/path&gt;&lt;path d=&quot;M869 864c-5.9 0-11.8-2.2-16.3-6.7l-83.5-83.5c-9-9-9-23.5 0-32.5s23.5-9 32.5 0l83.5 83.5c9 9 9 23.5 0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iconfont {
            get {
                return ResourceManager.GetString("iconfont", resourceCulture);
            }
        }
    }
}
